
>> NEW <<:

https://www.youtube.com/watch?v=N-cgHq1z8p8
https://www.youtube.com/watch?v=pkZ8OfgRig0
https://www.youtube.com/user/hymineruva/videos

CAD & INO files:
https://drive.google.com/file/d/0B4UkEGkFwwUQS05qMXVmOXBwY2M/view

Software:
https://github.com/Canta/book-scanning
(by: https://www.youtube.com/watch?v=T0yTWxATKE8)

Hiroshi Yanagisawa.﻿ Blog:
http://tges.blog117.fc2.com/blog-date-20141220.html
(his mail: y[].h[]@g..c..)


For the physical frame:

For the moving compartment:
- gipsplaat + waprnningsband (gamma)
- anti-glare plexi 3 mm (ru58)





OLD:

http://pidashcam.blogspot.nl/2013/09/configuration.html
http://www.arducam.com/multi-camera-adapter-module-raspberry-pi/
http://www.pyimagesearch.com/2016/01/18/multiple-cameras-with-the-raspberry-pi-and-opencv/
pidashcam.blogspot.nl/2013/10/wiring-button-some-leds-and-gps.html 
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=108881
http://www.instructables.com/id/Trigger-a-Webcam-with-a-button-and-Raspberry-Pi/?ALLSTEPS
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=127665 
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=129529 
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=50142
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=108881


# Physical setup:
http://makezine.com/2015/12/04/admittedly-simplistic-guide-raspberry-pi-vs-arduino/

Frame base:
http://www.instructables.com/id/Book-Scanner-Low-cost-easy-to-make-1000-pages-an-h/
(minimal contructionwork, lightweight, easily expandable into fully automatic movement by adding motors, low-cost)

Controlling the camera's, reading the images, putting them into the correct order,
converting the images into searchable pdf's, etc. - is a Raspberry Pi 3 B.

- The two camera's should be:
Trust trino HD

www.raspberrypi-spy.co.uk/2013/05/taking-hi-res-photos-with-the-pi-camera-module
https://www.raspberrypi.org/documentation/raspbian/applications/camera.md
https://www.raspberrypi.org/documentation/usage/camera/raspicam/raspistill.md/
www.pyimagesearch.com/2016/01/18/multiple-cameras-with-the-raspberry-pi-and-opencv/
www.pyimagesearch.com

- To trigger the camera's, mount a button on the side so that when pages are pressed a new set of captures
are taken.

- Inspiration: (check comments)
store.diybookscanner.org
https://www.raspberrypi.org/blog/raspberry-pi-controlled-book-scanner/


# Code setup:

- Installing x-bian: choose between raspbian, minibian, etc.
- Make a bash script that triggers:
-- Python script to:
0) understand start & end of 1 book (button pressed over 5 sec.?)
1) read button pressed
2) trigger image-capture commands
3) ensure correct order of files
4) paste all files together into one file (at the end)
5) copy file into backup, and convert into searchable pdf
6) optional: automatically email/upload to personal cloud
